version: 2.1

orbs:
  go: circleci/go@3.0.2

executors:
  go-executor:
    docker:
      - image: cimg/go:1.24.2
    environment:
      CGO_ENABLED: 1
      GOOS: linux
      GOARCH: amd64

jobs:
  lint:
    executor: go-executor
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:5cXrAzbjuZsbi6fCLIPU9XTddSqyuypQqChhB4Kj7jA"
      - run:
          name: Install Linters
          command: make install-tools
      - run:
          name: Configure Git for SSH
          command: |
            git config --global url."git@github.com:".insteadOf "https://github.com/"
            go env -w GOPRIVATE=github.com/CanobbioE/*
      - run:
          name: Run Linters
          command: make lint

workflows:
  version: 2
  lint:
    jobs:
      - lint:
          filters:
            tags:
              only: /.*/
